rtthread.siz:
	riscv64-unknown-elf-size --format=berkeley "rtthread.elf"
	riscv32-elf-xmaker -b rtthread.xm
	riscv32-elf-xmaker -b download.xm

clean2:
	-$(RM) $(CC_DEPS)$(C++_DEPS)$(C_UPPER_DEPS)$(CXX_DEPS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_UPPER_DEPS)$(C_DEPS)$(CPP_DEPS)
	-$(RM) $(OBJS) *.elf
	-@echo ' '


*.elf: $(wildcard D:/RT-ThreadStudio2000/workspace/10220/link.lds)
